version: '3.6'
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: hello-prisma
  postgres-migrations:
    build: .
    restart: on-failure
    depends_on:
      - postgres
    environment:
      DB_HOST: localhost
      DB_NAME: hello-prisma
volumes:
  db_data:
